### PR TITLE
Update dependencies (avro4s update)

### PR DESCRIPTION
**Pull request by alejandrohdezma**
## What does this change do?

Updates all the updatable dependencies to their latest versions, except the ones that involve updating to cats-effect 3.0:

- Update Scala version (this involved a bunch of `nowarn` annotations).
- Update `cats-effect` to `2.5.0`.
- Update organization for `log4cats` (is now under the [Typelevel organization](https://github.com/typelevel/log4cats)).
- Update `avro4s` to `4.0.7` (this involved a few removed parameters and `Decoder` and `Encoder` classes now including the `SchemaFor` (instead of handling it implicitly).

## Checklist

- [x] Reviewed the diff to look for typos, println and format errors.
- [x] Updated the docs accordingly.

### CODE REVIEW

**Review by fedefernandez — APPROVED** [review]
Looks good to me.

**Comment by juanpedromoreno** [comment]
Yes, it seems that's the problem. That scala version causes `scoverage` issues like [this](https://github.com/scoverage/scalac-scoverage-plugin/issues/305). It's not exactly that, but I believe it's related.

I checked it in this PR: https://github.com/higherkindness/mu-scala/pull/1184, where the error is different (Avro test failing, apparently).

Thanks @alejandrohdezma !

**Review by franciscodr — APPROVED** [review]
Great work! Thanks, @alejandrohdezma

**Comment by alejandrohdezma** [comment]
@juanpedromoreno downgrading Scala version again seemed to fixed the issue, but as you noticed the `RPCTests` failed :(

**Comment by alejandrohdezma** [comment]
Can someone that knows their way around this tests help me troubleshoot it? There are so many logs that I'm a bit lost

**Comment by alejandrohdezma** [comment]
@franciscodr managed to find the cause of the errors and the "solution". As said in https://github.com/higherkindness/mu-scala/pull/1183/commits/a232ee277d3551dde3c14d23782618b13ddf84e7, the only solution was to ignore the failing test. 

This test fails because of this update in `avro4s`: sksamuel/avro4s#594.

It is a corner case that will occur only if all the following applies:
- The user is generating IDLs from Scala code (it can never happen the other way around).
- A field in a request/response is using a `Coproduct`.
- Said `Coproduct` is using a generic type.
- Said field has a default value.

If all the previous checks, the generated schema will not contain the default value.

We discussed it and concluded that it is such a small case that we are safe to go down this road.

**Review by fedefernandez — APPROVED** [review]

**Review by juanpedromoreno — APPROVED** [review]

**Pull request merged**
