### PR TITLE
Rename idlgen to srcgen

### PR DESCRIPTION
**Pull request by naree**
## What this does?
idlgen renamed to srcgen

## Checklist

- [ ] Reviewed the diff to look for typos, println and format errors.
- [ ] Updated the docs accordingly.

### CODE REVIEW

**Comment by naree** [comment]
This PR should not be merged until the previous release issue sorting is finished by @cb372

**Comment by cb372** [comment]
You'll need to update the references to `idlgen` in `.travis.yml`. That's why the build is failing.

**Comment by naree** [comment]
@pepegar @juanpedromoreno @cb372 Should the name change be done with a major version change?

**Comment by juanpedromoreno** [comment]
@naree I think we can just do a minor version.

**Pull request merged**
